general:
  project_name: yolo_CP #test_yolo_gs_CP_lComb_nohead1_noCls
  #model_path: src/experiments_outputs/yolo_gs_COCO_nohead13_noCls_lComb/saved_models/best_model.h5
  model_type: st_yolo_x
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: True
  #gpu_memory_limit: 16 #24
  
  num_threads_tflite: 80
  #global_seed: 127

operation_mode: chain_tqe

dataset:
  name: PEDRo #COCO-OIDv6_gs #PEDRo
  class_names: [person]
  training_path: training_data/PEDRo/train  #training_data/coco2017_gs_person/train #training_data/PEDRo/train
  validation_path: training_data/PEDRo/val #training_data/coco2017_gs_person/val #training_data/PEDRo/val
  #validation_split: 0.11
  test_path: training_data/PEDRo/test #training_data/coco2017_gs_person/test_OIDv6 #training_data/PEDRo/test
  #quantization_path: /local/data/od_coco_2017_person/train
  quantization_split: 0.02

preprocessing:
   rescaling:
      scale: 1/255
      offset: 0
   resizing:
      aspect_ratio: fit
      interpolation: nearest
   color_mode: 'rgb'

data_augmentation:
  random_contrast:
    factor: 0.4
  random_brightness:
    factor: 0.3
  random_flip:
    mode: horizontal
  random_translation:
    width_factor: 0.15
    height_factor: 0.15
    fill_mode: reflect
    interpolation: nearest
  random_rotation:
    factor: 0.02
    fill_mode: reflect
    interpolation: nearest
  random_crop:
    crop_center_x: (0.25, 0.75)
    crop_center_y: (0.25, 0.75)
    crop_width: (0.6, 0.9)
    crop_height: (0.6, 0.9)
    change_rate: 0.9

training:
  #model:
    #input_shape: (192,192,1)
    #depth_mul: 0.33
    #width_mul: 0.25
    #pretrained_weights: /home/jovyan/yolo_x_nano_train/st_yolo_x_nano_192/st_yolo_x_nano_192_0.33_0.25_greyscale.h5
  resume_training_from: src/experiments_outputs/yolo_CP
  dropout: null
  batch_size: 800
  epochs: 400
  optimizer:
    Adam:
      learning_rate: 0.0025
  callbacks:
    LRWarmupCosineDecay:
      initial_lr: 1.0e-05
      warmup_steps: 20
      max_lr: 0.00125
      hold_steps: 20
      decay_steps: 300
      end_lr: 1.0e-06
    EarlyStopping:
      monitor: val_loss
      patience: 18
      restore_best_weights: true
      verbose: 1

postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: true
  max_detection_boxes: 100
  #network_stride: [16]
  
quantization:
  quantizer: TFlite_converter #TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float32
  #quantization_weights_type: int8
  #quantization_activations_type:
  granularity: per_channel  # Optional, defaults to "per_channel".
  #timeout: 
  optimize: True           # Optional, defaults to False.
  export_dir: quantized_models
  
evaluation:
    target: host

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/yolo_CP