general:
   model_path: https://github.com/stm32-hotspot/ultralytics/raw/refs/heads/main/examples/YOLOv8-STEdgeAI/stedgeai_models/pose_estimation/yolov8n_256_quant_pc_uf_pose_coco-st.tflite
   model_type: yolo_mpe

operation_mode: deployment

dataset:
   class_names: [person]
   keypoints: 17
   keypoints_file_path : ../application_code/pose_estimation/STM32MP-LINUX/Resources/keypoints_yolov8.txt
   test_path: ./datasets/coco_val_single_pose

preprocessing:
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15
   confidence_thresh: 0.5
   max_detection_boxes: 10
   NMS_thresh: 0.5

tools:
   stedgeai:
      version: 10.0.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe

deployment:
   c_project_path: ../application_code/pose_estimation/STM32MP-LINUX/
   board_deploy_path: /usr/local/pose-estimation
   verbosity: 1
   hardware_setup:
      serie: STM32MP2
      board: STM32MP257F-EV1
      ip_address: X.X.X.X

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}